services:
  tmodloader:
    image: hexlo/terraria-tmodloader-server:latest
    container_name: tmodloader
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - 7777:7777
    volumes:
      - ./tModLoader:/root/.local/share/Terraria/tModLoader
    environment:
      - AUTOCREATE=3             # 1 = Small, 2 = Medium, 3 = Large
      - WORLDNAME=CalamityWorld  # Nombre del mundo (sin .wld)
      - DIFFICULTY=2             # 0 = Normal, 1 = Expert, 2 = Master, 3 = Journey
      - PASSWORD=hello123
      - MOTD=Servidor con Mods 🎮
